require("dotenv").config({ path: require("path").resolve(__dirname, "../.env") });
const { connectDB } = require("../src/config/db");

const now = Date.now();
const daysAgo = (n) => new Date(now - n * 86400000).toISOString();
const daysFromNow = (n) => new Date(now + n * 86400000).toISOString();

const jobs = [
  {
    title: "Senior Backend Engineer",
    shortDescription: "Design and scale the APIs behind Elevora's core hiring platform.",
    fullDescription:
      "We're looking for a senior backend engineer to own our job-matching and applications services. You'll work with Node.js, Express, and MongoDB, and partner closely with the product team on the AI recommendation pipeline. Expect to design schemas, optimize queries at scale, and mentor two mid-level engineers.",
    location: "San Francisco, CA",
    type: "Full-time",
    category: "Engineering",
    experienceLevel: "Senior",
    salaryMin: 150000,
    salaryMax: 190000,
    currency: "USD",
    deadline: daysFromNow(30),
    imageUrl: "https://images.unsplash.com/photo-1611944212129-29977ae1398c?w=200&h=200&fit=crop",
    recruiterId: "seed-recruiter-1",
    recruiterName: "Northwind Labs",
    createdAt: daysAgo(1),
  },
  {
    title: "Frontend Engineer (React)",
    shortDescription: "Build the recruiter and job-seeker dashboards used every day.",
    fullDescription:
      "You'll build and maintain our Next.js + TypeScript frontend, working closely with design on the job listing, explore, and dashboard experiences. Strong React fundamentals and an eye for accessible, responsive UI are a must.",
    location: "Remote",
    type: "Full-time",
    category: "Engineering",
    experienceLevel: "Mid",
    salaryMin: 110000,
    salaryMax: 140000,
    currency: "USD",
    deadline: daysFromNow(21),
    imageUrl: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=200&h=200&fit=crop",
    recruiterId: "seed-recruiter-1",
    recruiterName: "Northwind Labs",
    createdAt: daysAgo(2),
  },
  {
    title: "Product Designer",
    shortDescription: "Shape the end-to-end experience for job seekers and recruiters.",
    fullDescription:
      "As our second product designer, you'll drive UX for the job search and application flows, run usability sessions with real recruiters, and maintain our design system in Figma. You'll work directly with engineering to ship polished, responsive UI.",
    location: "New York, NY",
    type: "Full-time",
    category: "Design",
    experienceLevel: "Mid",
    salaryMin: 95000,
    salaryMax: 125000,
    currency: "USD",
    deadline: daysFromNow(25),
    imageUrl: "https://images.unsplash.com/photo-1572044162444-ad60f128bdea?w=200&h=200&fit=crop",
    recruiterId: "seed-recruiter-2",
    recruiterName: "Brightline Studio",
    createdAt: daysAgo(4),
  },
  {
    title: "UX Research Intern",
    shortDescription: "Support user interviews and usability testing for our hiring tools.",
    fullDescription:
      "A 12-week internship supporting our research team: recruiting participants, moderating interviews, and synthesizing findings into actionable recommendations for the product and design teams.",
    location: "Remote",
    type: "Internship",
    category: "Design",
    experienceLevel: "Entry",
    salaryMin: 30000,
    salaryMax: 40000,
    currency: "USD",
    deadline: daysFromNow(14),
    imageUrl: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=200&h=200&fit=crop",
    recruiterId: "seed-recruiter-2",
    recruiterName: "Brightline Studio",
    createdAt: daysAgo(3),
  },
  {
    title: "Growth Marketing Manager",
    shortDescription: "Own acquisition campaigns that bring recruiters and candidates to Elevora.",
    fullDescription:
      "You'll plan and execute paid and organic campaigns across search, social, and content, with a focus on lowering cost-per-signup for both recruiters and job seekers. Comfortable with analytics tooling and A/B testing.",
    location: "Austin, TX",
    type: "Full-time",
    category: "Marketing",
    experienceLevel: "Senior",
    salaryMin: 100000,
    salaryMax: 130000,
    currency: "USD",
    deadline: daysFromNow(18),
    imageUrl: "https://images.unsplash.com/photo-1533750349088-cd871a92f312?w=200&h=200&fit=crop",
    recruiterId: "seed-recruiter-3",
    recruiterName: "Fieldstone Media",
    createdAt: daysAgo(6),
  },
  {
    title: "Content Marketing Specialist",
    shortDescription: "Write career and hiring content that ranks and converts.",
    fullDescription:
      "Own our blog and resource library: career guides for job seekers, hiring playbooks for recruiters, and SEO-driven landing pages. Familiarity with keyword research tools expected.",
    location: "Remote",
    type: "Part-time",
    category: "Marketing",
    experienceLevel: "Mid",
    salaryMin: 45000,
    salaryMax: 60000,
    currency: "USD",
    deadline: daysFromNow(20),
    imageUrl: "https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=200&h=200&fit=crop",
    recruiterId: "seed-recruiter-3",
    recruiterName: "Fieldstone Media",
    createdAt: daysAgo(5),
  },
  {
    title: "Enterprise Account Executive",
    shortDescription: "Sell Elevora's recruiter tools to mid-market and enterprise HR teams.",
    fullDescription:
      "Own the full sales cycle for enterprise accounts, from discovery through close. You'll partner with our solutions team on custom onboarding for large hiring teams and carry a quarterly quota.",
    location: "Chicago, IL",
    type: "Full-time",
    category: "Sales",
    experienceLevel: "Senior",
    salaryMin: 90000,
    salaryMax: 120000,
    currency: "USD",
    deadline: daysFromNow(28),
    imageUrl: "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=200&h=200&fit=crop",
    recruiterId: "seed-recruiter-4",
    recruiterName: "Harborview Group",
    createdAt: daysAgo(7),
  },
  {
    title: "Sales Development Representative",
    shortDescription: "Qualify inbound leads and book demos for our account executives.",
    fullDescription:
      "Entry-level sales role focused on outbound prospecting and inbound lead qualification for HR and recruiting teams. Great stepping stone into a full sales career with a clear promotion path.",
    location: "Remote",
    type: "Full-time",
    category: "Sales",
    experienceLevel: "Entry",
    salaryMin: 50000,
    salaryMax: 65000,
    currency: "USD",
    deadline: daysFromNow(15),
    imageUrl: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=200&h=200&fit=crop",
    recruiterId: "seed-recruiter-4",
    recruiterName: "Harborview Group",
    createdAt: daysAgo(2),
  },
  {
    title: "Data Analyst, Marketplace",
    shortDescription: "Analyze hiring funnel data to improve job-seeker to recruiter matching.",
    fullDescription:
      "You'll build dashboards and run analyses on application conversion, time-to-hire, and search relevance. SQL fluency and experience with a BI tool (Looker, Metabase, or similar) required.",
    location: "Boston, MA",
    type: "Full-time",
    category: "Data",
    experienceLevel: "Mid",
    salaryMin: 100000,
    salaryMax: 130000,
    currency: "USD",
    deadline: daysFromNow(22),
    imageUrl: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=200&h=200&fit=crop",
    recruiterId: "seed-recruiter-1",
    recruiterName: "Northwind Labs",
    createdAt: daysAgo(3),
  },
  {
    title: "Machine Learning Engineer",
    shortDescription: "Build the recommendation models behind our AI job-matching engine.",
    fullDescription:
      "Own the ranking models that power personalized job recommendations. You'll work with our data science team on feature engineering, offline evaluation, and shipping models into production behind the Express API.",
    location: "Remote",
    type: "Full-time",
    category: "Data",
    experienceLevel: "Senior",
    salaryMin: 160000,
    salaryMax: 200000,
    currency: "USD",
    deadline: daysFromNow(35),
    imageUrl: "https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=200&h=200&fit=crop",
    recruiterId: "seed-recruiter-1",
    recruiterName: "Northwind Labs",
    createdAt: daysAgo(1),
  },
  {
    title: "Product Manager, Recruiter Tools",
    shortDescription: "Lead the roadmap for job posting, applicant tracking, and recruiter dashboards.",
    fullDescription:
      "You'll define and ship the recruiter-facing side of Elevora: job posting flows, applicant management, and AI-assisted content tools. Work directly with design, engineering, and a panel of recruiter customers.",
    location: "New York, NY",
    type: "Full-time",
    category: "Product",
    experienceLevel: "Lead",
    salaryMin: 145000,
    salaryMax: 180000,
    currency: "USD",
    deadline: daysFromNow(27),
    imageUrl: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=200&h=200&fit=crop",
    recruiterId: "seed-recruiter-2",
    recruiterName: "Brightline Studio",
    createdAt: daysAgo(5),
  },
  {
    title: "Associate Product Manager",
    shortDescription: "Support feature delivery across the job seeker experience.",
    fullDescription:
      "A great first PM role: you'll own smaller features end-to-end (saved jobs, application status, notifications) while learning from senior PMs on the team. Strong written communication and curiosity about user problems expected.",
    location: "Remote",
    type: "Full-time",
    category: "Product",
    experienceLevel: "Entry",
    salaryMin: 80000,
    salaryMax: 100000,
    currency: "USD",
    deadline: daysFromNow(19),
    imageUrl: "https://images.unsplash.com/photo-1531482615713-2afd69097998?w=200&h=200&fit=crop",
    recruiterId: "seed-recruiter-2",
    recruiterName: "Brightline Studio",
    createdAt: daysAgo(4),
  },
  {
    title: "Customer Support Specialist",
    shortDescription: "Help job seekers and recruiters get the most out of Elevora.",
    fullDescription:
      "Front-line support via chat and email for both sides of the marketplace — troubleshooting login issues, application questions, and job-posting problems. You'll also flag recurring issues to product.",
    location: "Denver, CO",
    type: "Full-time",
    category: "Customer Support",
    experienceLevel: "Entry",
    salaryMin: 42000,
    salaryMax: 52000,
    currency: "USD",
    deadline: daysFromNow(12),
    imageUrl: "https://images.unsplash.com/photo-1553877522-43269d4ea984?w=200&h=200&fit=crop",
    recruiterId: "seed-recruiter-4",
    recruiterName: "Harborview Group",
    createdAt: daysAgo(6),
  },
  {
    title: "Freelance Technical Recruiter",
    shortDescription: "Source and screen engineering candidates on a contract basis.",
    fullDescription:
      "3-month contract sourcing and initial-screening engineering candidates for our internal hiring push. Prior technical recruiting experience and comfort with high-volume sourcing tools required.",
    location: "Remote",
    type: "Contract",
    category: "Customer Support",
    experienceLevel: "Mid",
    salaryMin: 60000,
    salaryMax: 80000,
    currency: "USD",
    deadline: daysFromNow(10),
    imageUrl: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=200&h=200&fit=crop",
    recruiterId: "seed-recruiter-3",
    recruiterName: "Fieldstone Media",
    createdAt: daysAgo(8),
  },
];

async function seed() {
  const db = await connectDB();
  const collection = db.collection("jobs");
  await collection.deleteMany({});
  const result = await collection.insertMany(jobs);
  console.log(`Inserted ${result.insertedCount} jobs.`);
}

seed()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error("Seeding failed:", err);
    process.exit(1);
  });
